device: "cpu"
sampler: "heun"
num_steps: 20
output_path: "/data/dust/user/dayhallh/data/CaloClouds_diffusion"

preprocessing:
  conditioning:
    - - Partial
      - split_indices: [1]
        components:
          - - [Log, {alpha: 0.5}]
            - - Affine
              - inverse_scale: ["data", "log_incidentE_std"]
                neg_shift: ["data", "log_incidentE_mean"]
          - null
  features:
    - - Partial
      - split_indices: [1, 2, 3]
        components:
          - - [Affine, {inverse_scale: ["data", "Xstd"], neg_shift: ["data", "Xmean"]}]
          - - [Affine, {inverse_scale: ["data", "Ystd"], neg_shift: ["data", "Ymean"]}]
          - - [Affine, {inverse_scale: ["data", "Zstd"], neg_shift: ["data", "Zmean"]}]
          - - [Log, {alpha: 0.5}]
            - - Affine
              - scale: ["data", "log_Estd"]
                shift: ["data", "log_Emean"]

model:
  logarithmic_point_energy: true
  cond_dim: 4
  cond_features: ["incident_energy", "incident_direction"]
  feature_dim: 4
  rho: 7.0
  s_churn: 0.0
  s_noise: 1.0
  sigma_min: 0.002
  sigma_max: 80.0

data:
  dataset_path: "/data/dust/group/ilc/sft-ml/datasets/sim-E1261AT600AP180-180/sim-E1261AT600AP180-180_file_{}.slcio.hdf5"
  test_range_start: 0
  test_range_end: 10
  val_range_start: 10
  val_range_end: 20
  train_range_start: 20
  train_range_end: 90

  format: "padded_unordered"
  roll_axis: true
  padding: "front"
  points_key: "events"
  incident_pdg_key: null
  incident_energy_key: "energy"
  incident_direction_key: "p_norm_local"
  n_points_key: "n_points"

  Xmin: -250  # in data coords
  Xmax: 250  # in data coords
  Ymin: -250  # in data coords
  Ymax: 250  # in data coords
  Xmin_in_detector: -250  # in detector coords
  Xmax_in_detector: 250  # in detector coords
  Zmin_in_detector: -250 # in detector coords
  Zmax_in_detector: 250  # in detector coords


  Xmean: -0.0074305227
  Xstd: 21.608465
  Ymean: -0.21205868
  Ystd: 22.748442
  Zmean: 12.359252
  Zstd: 5.305082

  log_Emean: -8.431133
  log_Estd: 1.251827

  log_incidentE_mean: 3.87
  log_incidentE_std: 0.934

  orientation: "hdf5:xyz==local:xyz"
  cell_thickness: 1.0
  cell_size:  5.0883331298828125
  layer_bottom_pos: [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29.]
  divisions_per_cell: 5

  gun_xyz_pos: [0.0, 1811., 0.0]
  gun_xyz_pos_in_detector: [0.0, 1811., -50.0]

detector:
  Ymin: 1811
  orientation: "hdf5:xyz==global:zxy"
  cell_thickness: 0.5250244140625
  cell_size:  5.0883331298828125
  layer_bottom_pos: [1811.34020996, 1814.46508789, 1823.81005859, 1826.93505859, 1836.2800293, 1839.4050293, 1848.75, 1851.875, 1861.2199707 , 1864.3449707, 1873.68994141, 1876.81494141, 1886.16003418, 1889.28503418, 1898.63000488, 1901.75500488, 1911.09997559, 1914.22497559, 1923.56994629, 1926.69494629, 1938.14001465, 1943.36499023, 1954.81005859, 1960.03503418, 1971.47998047, 1976.70495605, 1988.15002441, 1993.375, 2004.81994629, 2010.04504395]

training:
  dtype: "float32"
  batch_size: 32
  max_points_per_event: 6000
  sigma_data: 0.5
  sigma_sample_density:
    type: "lognormal"
    mean: -1.2
    std: 1.2
  retain_quantized: true  # this dataset is fuzzed on disk
  diffusion_loss: "l2"
  num_workers: 1
  shuffle_data: true
  optimiser: "Adam"
  optimiser_kwargs:
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 0.00000001
  end_epoch: 100
  start_lr: 0.001
  end_lr: 0.00001
  ema_power: 0.6667
  ema_max_value: 0.9999
  max_grad_norm: 10.0
  checkpoint_time_interval_min: 30
  checkpoint_batch_interval: -1


  
